# prefixキーをC-tに変更
set -g prefix C-t
unbind C-b
bind C-t send-prefix

# 設定ファイルをリロード
bind 'r' source-file ~/.tmux.conf \; display "Config Reloaded!"

# ウインドウ番号を詰める
set -g renumber-windows on

# カレントパスの情報を引き継ぐ
bind '"' split-window -vc '#{pane_current_path}'
bind '%' split-window -hc '#{pane_current_path}'
bind 'c' new-window -c '#{pane_current_path}'

# 色/スタイルの設定
# ステータスライン
set -g status-style "fg=black,bg=blue"
set -g status-right "[#(git -C #{pane_current_path} rev-parse --abbrev-ref HEAD 2>/dev/null || echo -)] %Y/%m/%d(%a) %H:%M"
set -g status-interval 5

# ペイン
set -g pane-border-style "fg=blue,bg=default"
set -g pane-active-border-style "fg=blue,bg=default"
# ウインドウモード（コピーモード）
set -wg mode-style "fg=black,bg=blue"

# マウススクロールを有効に
set -g mouse on

# クリップボードをMacと共有
set -s copy-command 'pbcopy'
set -g set-clipboard on

# コピーモードでvimキーバインドを使う
setw -g mode-keys vi
# vで選択を始める
bind -T copy-mode-vi v send-keys -X begin-selection
# 選択してyかEnterでクリップボードにコピー
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
unbind -T copy-mode-vi Enter
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel

